### ISSUE TITLE
Empty togo item

### ISSUE THREAD

**Issue by HorbachAndrii** [mariia-kovalova/to-do-list#1]
Users can create a new todo item by double click "Create" button

<img width="943" alt="image" src="https://user-images.githubusercontent.com/36758882/227012357-e73de214-a6f8-45c5-a6b9-d789bfd13824.png">

**Comment by mariia-kovalova** [comment]
Thanks) I'll fix that)

**Comment by mariia-kovalova** [comment]
Fixed it by adding one more checkpoint.
