### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by HorbachAndrii** [mariia-kovalova/to-do-list#2]
Will be better if we show a loader after changing the input state

https://github.com/mariia-kovalova/to-do-list/blob/76785e668d8d91ea453e2c615b87377442461905/src/components/TodoItem/TodoItem.jsx#L40

**Comment by mariia-kovalova** [comment]
That's a great idea) I'll work on it)

**Comment by mariia-kovalova** [comment]
Done!)
